### ISSUE TITLE
TODO for paper

### ISSUE THREAD

**Issue by damonge** [damonge/schNell#3]
- [x] Rerun inverse noise variance maps and create videos
- [x] Make antenna pattern plots for T/A/E for website?
- [x] New release pre-arXiv
- [x] Plots for rtd
